/**
 * This file is AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
/* eslint-disable */
/* tslint:disable */
import { HttpResponse, http } from "msw";
import { faker } from "@faker-js/faker";

faker.seed(1);

const baseURL = "http://localhost:3000";
const MAX_ARRAY_LENGTH = 20;

let i = 0;
const next = () => {
  if (i === Number.MAX_SAFE_INTEGER - 1) {
    i = 0;
  }
  return i++;
};

export const handlers = [
  http.put(`${baseURL}/pet`, async () => {
    const resultArray = [
      [await getUpdatePet200Response(), { status: 200 }],
      [undefined, { status: 400 }],
      [undefined, { status: 404 }],
      [undefined, { status: 405 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.post(`${baseURL}/pet`, async () => {
    const resultArray = [
      [await getAddPet200Response(), { status: 200 }],
      [undefined, { status: 405 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.get(`${baseURL}/pet/findByStatus`, async () => {
    const resultArray = [
      [await getFindPetsByStatus200Response(), { status: 200 }],
      [undefined, { status: 400 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.get(`${baseURL}/pet/findByTags`, async () => {
    const resultArray = [
      [await getFindPetsByTags200Response(), { status: 200 }],
      [undefined, { status: 400 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.get(`${baseURL}/pet/:petId`, async () => {
    const resultArray = [
      [await getGetPetById200Response(), { status: 200 }],
      [undefined, { status: 400 }],
      [undefined, { status: 404 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.post(`${baseURL}/pet/:petId`, async () => {
    const resultArray = [[undefined, { status: 405 }]];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.delete(`${baseURL}/pet/:petId`, async () => {
    const resultArray = [[undefined, { status: 400 }]];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.post(`${baseURL}/pet/:petId/uploadImage`, async () => {
    const resultArray = [[await getUploadFile200Response(), { status: 200 }]];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.get(`${baseURL}/store/inventory`, async () => {
    const resultArray = [[await getGetInventory200Response(), { status: 200 }]];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.post(`${baseURL}/store/order`, async () => {
    const resultArray = [
      [await getPlaceOrder200Response(), { status: 200 }],
      [undefined, { status: 405 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.get(`${baseURL}/store/order/:orderId`, async () => {
    const resultArray = [
      [await getGetOrderById200Response(), { status: 200 }],
      [undefined, { status: 400 }],
      [undefined, { status: 404 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.delete(`${baseURL}/store/order/:orderId`, async () => {
    const resultArray = [
      [undefined, { status: 400 }],
      [undefined, { status: 404 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.post(`${baseURL}/user`, async () => {
    const resultArray = [
      [await getCreateUserdefaultResponse(), { status: NaN }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.post(`${baseURL}/user/createWithList`, async () => {
    const resultArray = [
      [await getCreateUsersWithListInput200Response(), { status: 200 }],
      [undefined, { status: NaN }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.get(`${baseURL}/user/login`, async () => {
    const resultArray = [
      [await getLoginUser200Response(), { status: 200 }],
      [undefined, { status: 400 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.get(`${baseURL}/user/logout`, async () => {
    const resultArray = [[undefined, { status: NaN }]];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.get(`${baseURL}/user/:username`, async () => {
    const resultArray = [
      [await getGetUserByName200Response(), { status: 200 }],
      [undefined, { status: 400 }],
      [undefined, { status: 404 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.put(`${baseURL}/user/:username`, async () => {
    const resultArray = [[undefined, { status: NaN }]];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
  http.delete(`${baseURL}/user/:username`, async () => {
    const resultArray = [
      [undefined, { status: 400 }],
      [undefined, { status: 404 }],
    ];

    return HttpResponse.json(...resultArray[next() % resultArray.length]);
  }),
];

export function getUpdatePet200Response() {
  return {
    id: 10,
    name: "doggie",
    category: {
      id: 1,
      name: "Dogs",
    },
    photoUrls: [
      ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
    ].map((_) => faker.lorem.words()),
    tags: [
      ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
    ].map((_) => ({
      id: faker.number.int(),
      name: faker.person.fullName(),
    })),
    status: faker.helpers.arrayElement(["available", "pending", "sold"]),
  };
}

export function getAddPet200Response() {
  return {
    id: 10,
    name: "doggie",
    category: {
      id: 1,
      name: "Dogs",
    },
    photoUrls: [
      ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
    ].map((_) => faker.lorem.words()),
    tags: [
      ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
    ].map((_) => ({
      id: faker.number.int(),
      name: faker.person.fullName(),
    })),
    status: faker.helpers.arrayElement(["available", "pending", "sold"]),
  };
}

export function getFindPetsByStatus200Response() {
  return [
    ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
  ].map((_) => ({
    id: 10,
    name: "doggie",
    category: {
      id: 1,
      name: "Dogs",
    },
    photoUrls: [
      ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
    ].map((_) => faker.lorem.words()),
    tags: [
      ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
    ].map((_) => ({
      id: faker.number.int(),
      name: faker.person.fullName(),
    })),
    status: faker.helpers.arrayElement(["available", "pending", "sold"]),
  }));
}

export function getFindPetsByTags200Response() {
  return [
    ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
  ].map((_) => ({
    id: 10,
    name: "doggie",
    category: {
      id: 1,
      name: "Dogs",
    },
    photoUrls: [
      ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
    ].map((_) => faker.lorem.words()),
    tags: [
      ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
    ].map((_) => ({
      id: faker.number.int(),
      name: faker.person.fullName(),
    })),
    status: faker.helpers.arrayElement(["available", "pending", "sold"]),
  }));
}

export function getGetPetById200Response() {
  return {
    id: 10,
    name: "doggie",
    category: {
      id: 1,
      name: "Dogs",
    },
    photoUrls: [
      ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
    ].map((_) => faker.lorem.words()),
    tags: [
      ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
    ].map((_) => ({
      id: faker.number.int(),
      name: faker.person.fullName(),
    })),
    status: faker.helpers.arrayElement(["available", "pending", "sold"]),
  };
}

export function getUploadFile200Response() {
  return {
    code: faker.number.int(),
    type: faker.lorem.words(),
    message: faker.lorem.words(),
  };
}

export function getGetInventory200Response() {
  return [...new Array(5).keys()]
    .map((_) => ({ [faker.lorem.word()]: faker.number.int() }))
    .reduce((acc, next) => Object.assign(acc, next), {});
}

export function getPlaceOrder200Response() {
  return {
    id: 10,
    petId: 198772,
    quantity: 7,
    shipDate: faker.date.past(),
    status: "approved",
    complete: faker.datatype.boolean(),
  };
}

export function getGetOrderById200Response() {
  return {
    id: 10,
    petId: 198772,
    quantity: 7,
    shipDate: faker.date.past(),
    status: "approved",
    complete: faker.datatype.boolean(),
  };
}

export function getCreateUserdefaultResponse() {
  return {
    id: 10,
    username: "theUser",
    firstName: "John",
    lastName: "James",
    email: "john@email.com",
    password: "12345",
    phone: "12345",
    userStatus: 1,
  };
}

export function getCreateUsersWithListInput200Response() {
  return {
    id: 10,
    username: "theUser",
    firstName: "John",
    lastName: "James",
    email: "john@email.com",
    password: "12345",
    phone: "12345",
    userStatus: 1,
  };
}

export function getLoginUser200Response() {
  return faker.lorem.words();
}

export function getGetUserByName200Response() {
  return {
    id: 10,
    username: "theUser",
    firstName: "John",
    lastName: "James",
    email: "john@email.com",
    password: "12345",
    phone: "12345",
    userStatus: 1,
  };
}
