name: on issue opened

on:
  pull_request_review_comment:
    types: [created]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = await github.rest.pulls.listReviewComments({ 
              owner: 'Henry-Hong',
              repo: 'i-am-not-a-junior-frontend',
              pull_number: 2,
            });

            const recentComment = result.data?.at(-1).body;

            if(recentComment.includes('NTC')) {
              await github.rest.issues.addLabels({
                owner: 'Henry-Hong',
                repo: 'i-am-not-a-junior-frontend',
                issue_number: 2,
                labels: ['need-to-change'],
              });
            }

# github.rest.pulls.listReviewComments({
#   owner: context.repo.owner,
#   repo: context.repo.repo,
#   pull_number: context.issue.number,
# })

# owner,
# repo,
# pull_number,
# review_id,
