name: on issue opened

on:
  issue_comment:
    types: [created]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(context)
            return
            github.rest.pulls.listCommentsForReview({ 
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.pull.number,
              body: '👋 Thanks for the comment!',
            })

            github.rest.pulls.listReviewComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            })

#             pulls.listCommentsForReview({
#   owner,
#   repo,
#   pull_number,
#   review_id,
# });
