name: on issue opened

on:
  issue_comment:
    types: [created]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = awaitgithub.rest.pulls.listCommentsForReview({ 
              owner: context.repository.owner,
              repo: context.repository.name,
              pull_number: context.issue.number,
            })

# github.rest.pulls.listReviewComments({
#   owner: context.repo.owner,
#   repo: context.repo.repo,
#   pull_number: context.issue.number,
# })

# owner,
# repo,
# pull_number,
# review_id,
